for mac

diff --git a/custom/user/jlabarthe/rc.d/090-gpfw b/custom/user/jlabarthe/rc.d/090-gpfw
--- a/custom/user/jlabarthe/rc.d/090-gpfw
+++ b/custom/user/jlabarthe/rc.d/090-gpfw
@@ -1,35 +1,75 @@
 #export PATH=/datas/devkits/pybin-20170509-2127-6708fb1:$PATH
-export PATH=/datas/gopro/PYBIN/release:$PATH
-export PATH=/datas/devkits/gcc-arm-none-eabi-4_9-2015q3-m9m/bin:$PATH
+export PATH=$HOME/datas/gopro/PYBIN/release:$PATH
+export PATH=$HOME/datas/devkits/gcc-arm-none-eabi-4_9-2015-q3/bin:$PATH
+export PATH=$HOME/datas/devkits/gcc-arm-gp1-eabihf-4_9-2015q3/bin:$PATH
+
+export MYENV_REFERENCE_ROOT_DIR=$HOME/datas/gopro/reference
+export MYENV_GIT_REFERENCE_ROOT_DIR=$MYENV_REFERENCE_ROOT_DIR/git_objects
+export PYBIN_GLOBAL_OBJECT_DIR=$MYENV_REFERENCE_ROOT_DIR/pybin_objects
+
+export BANZAI_USE_CCACHE=y
+
+getTTYName() {
+   echo "$(find /dev -name 'tty.usbmodem*' 2>/dev/null)"
+}
 
 b() {
-	Type=ACM
+	Type=AUTO
 	PortNumber=0
+	if [ "$1" = "-auto" ]; then Type=AUTO; shift; fi;
 	if [ "$1" = "-acm" ]; then Type=ACM; shift; fi;
 	if [ "$1" = "-usb" ]; then Type=USB; shift; fi;
 	if [ "$1" = "-1" ]; then PortNumber=1; shift; fi;
-	echo "$@" > /dev/tty${Type}${PortNumber}
+
+	if [ "$Type" = "AUTO" ]; then ttyName=$(getTTYName); else ttyName=/dev/tty${Type}${PortNumber}; fi
+	
+	if [ "$ttyName" = "" ]; then
+		echo "Command cannot be sent (not tty is active)"
+		return 1
+	else
+		echo "$@" > $ttyName
+	fi
+}
+
+bn() {
+    ssh root@192.168.0.202 /usr/local/gopro/bin/gpdevSendCmd TC \"$(echo $@)\"
 }
 
 gpcom() {
-	Type=ACM
+	Type=AUTO
 	PortNumber=0
 	Loop=y
+	if [ "$1" = "-auto" ]; then Type=AUTO; shift; fi;
 	if [ "$1" = "-acm" ]; then Type=ACM; shift; fi;
-	if [ "$1" = "-usb" ]; then Type=USB; shift; fi;
+	if [ "$1" = "-usb" ]; then Type=.usbserial-FT3XNKVJ; shift; fi;
 	if [ "$1" = "-loop" ]; then Loop=y; shift; fi;
 	if [ "$1" = "-1" ]; then PortNumber=1; shift; fi;
+	if [ "$Type" = "AUTO" ]; then ttyName=$(getTTYName); else ttyName=/dev/tty${Type}${PortNumber}; fi
 	if [ "$Loop" = "y" ]; then
 		while [ 1 ]; do
-			picocom -b 115200 --imap lfcrlf /dev/tty${Type}${PortNumber}
-			if [ $? -eq 0 ]; then break; fi;
-			echo "Waiting for /dev/tty${Type}${PortNumber} to come back alive ..."
-			while [ 1 ]; do
-				if [ -e /dev/tty${Type}${PortNumber} ]; then break; fi;
-				sleep 0.5 
-			done
+			if [ "$ttyName" = "" ]; then
+				echo "No tty is active, waiting one to come alive ..."
+				while [ 1 ]; do
+					ttyName=$(getTTYName)
+					if [ "$ttyName" != "" ]; then break; fi;
+					sleep 0.5
+				done
+			else	
+				picocom -b 115200 --imap lfcrlf $ttyName
+				if [ $? -eq 0 ]; then break; fi;
+				echo "Waiting for $ttyName to come back alive ..."
+				while [ 1 ]; do
+					if [ -e $ttyName ]; then break; fi;
+					sleep 0.5 
+				done
+			fi
 		done
 	else
-		picocom -b 115200 --imap lfcrlf /dev/tty${Type}${PortNumber}
+		if [ "$ttyName" = "" ]; then
+			echo "No tty is active"
+			return 1
+		else
+			picocom -b 115200 --imap lfcrlf $ttyName
+		fi
 	fi
 }
